# Generated by Django 5.0.7 on 2024-07-22 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=20)),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('amount', models.BigIntegerField(verbose_name='مقدار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرج',
                'verbose_name_plural': 'خرج ها',
            },
        ),
    ]
